In [4]:
# import numpy as np

# # Decompose symmetric matrix A into A = X J X.T
# # A : Symmetric matrix of shape (n, n)
# # x1: Initial normalized vector x1 with x1.T x1 = 1.
# # X : Orthogonal matrix of eigenvectors.
# # J : Tridiagonal matrix

# def lanczos_algorithm(A, x1):
#     n = A.shape[0]
#     X = np.zeros((n, n))
#     J = np.zeros((n, n))
#     X[:, 0] = x1   # Initialize x1 as the first column of X
#     a = np.zeros(n)
#     b = np.zeros(n - 1)
#     a[0] = np.dot(x1.T, np.dot(A, x1))  # Compute a1, first diagonal entry

   
#     for i in range(1, n):   # Iterative process for i = 1, ..., n-1
#         if i == 1:
#             z_i = A @ X[:, i - 1] - a[i - 1] * X[:, i - 1]
#         else:
#             z_i = (
#                 A @ X[:, i - 1]
#                 - a[i - 1] * X[:, i - 1]
#                 - b[i - 2] * X[:, i - 2]
#             )

#         # Compute b_i as the norm of z_i
#         b[i - 1] = np.linalg.norm(z_i)

#         # Normalize z_i to get x_{i+1}
#         if b[i - 1] != 0:
#             X[:, i] = z_i / b[i - 1]

#         # Compute a_{i+1}
#         a[i] = X[:, i].T @ A @ X[:, i]

#     # Construct J as the tridiagonal matrix with a_i on the diagonal and b_i on the sub/superdiagonal
#     for i in range(n):
#         J[i, i] = a[i]
#         if i < n - 1:
#             J[i, i + 1] = b[i]
#             J[i + 1, i] = b[i]

#     return X, J

# # Example usage
# if __name__ == "__main__":
#     # Example symmetric matrix A
#     A = np.array([
#         [1, 1, 1, 1],
#         [1, 2, 1, 1],
#         [1, 1, 3, 4],
#         [1, 1, 4, 1]
#     ])

#     # Initial vector x1 (normalized)
#     x1 = np.array([1, 0, 0, 0])

#     # Decompose A
#     X, J = lanczos_algorithm(A, x1)

#     print("Orthogonal matrix X:")
#     print(X)
#     print("\nDiagonal matrix J:")
#     print(J)

#     # Verify decomposition
#     print("\nReconstructed A:")


In [5]:
import numpy as np
# Decompose symmetric matrix A into A = X J X.T
# A : Symmetric matrix of shape (n, n)
# x1: Initial normalized vector x1 with x1.T x1 = 1.
# X : Orthogonal matrix of eigenvectors.
# J : Tridiagonal matrix

def lanczos_algorithm(A, x1):
    n = A.shape[0]
    X = np.zeros((n, n))
    J = np.zeros((n, n))
    X[:, 0] = x1   # Initialize x1 as the first column of X
    a = np.zeros(n)
    b = np.zeros(n - 1)
    a[0] = np.dot(x1.T, np.dot(A, x1))  # Compute a1, first diagonal entry

    for i in range(1, n):   # Iterative process for i = 1, ..., n-1
        if i == 1:
            z_i = np.dot(A, X[:, i - 1]) - a[i - 1] * X[:, i - 1]   # compute zi
        else:
            z_i = (np.dot(A, X[:, i - 1]) - a[i - 1] * X[:, i - 1]- b[i - 2] * X[:, i - 2])

       
        b[i - 1] = np.linalg.norm(z_i)   # Compute b_i as the norm of z_i
        if b[i - 1] != 0:                    # Normalize z_i to get x_{i+1}
            X[:, i] = z_i / b[i - 1]

       
        a[i] = np.dot(X[:, i].T, np.dot(A, X[:, i]))   # Compute a_{i+1}

   
    for i in range(n):        # Construct J as the tridiagonal matrix
        J[i, i] = a[i]
        if i < n - 1:
            J[i, i + 1] = b[i]
            J[i + 1, i] = b[i]

    return X, J
np.set_printoptions(precision=2, suppress=True)

#(1) Example symmetric matrix A
A = np.array([
    [1, 1, 1, 1],
    [1, 2, 1, 1],
    [1, 1, 3, 4],
    [1, 1, 4, 1]
])

x1 = np.array([1, 0, 0, 0])

X, J = lanczos_algorithm(A, x1)

print("Orthogonal matrix X=")
print(X)
print("\nTridiagonal matrix J=")
print(J)

# Verify decomposition
print("\nVerification = A=")
print(np.dot(np.dot(X, J), X.T))

#(2) Example symmetric matrix A
B = np.array([
    [1, 1, 0, 0],
    [1, 2, 1, 0],
    [0, 1, 3, 4],
    [0, 0, 4, 1]
])

x1 = np.array([1, 0, 0, 0])

X_1, J_1 = lanczos_algorithm(B, x1)

print("Orthogonal matrix X=")
print(X_1)
print("\nTridiagonal matrix J=")
print(J_1)

# Verify decomposition
print("\nVerification = B=")
print(np.dot(np.dot(X_1, J_1), X_1.T))

Orthogonal matrix X=
[[ 1.    0.    0.   -0.  ]
 [ 0.    0.58 -0.71 -0.41]
 [ 0.    0.58  0.71 -0.41]
 [ 0.    0.58 -0.    0.82]]

Tridiagonal matrix J=
[[ 1.    1.73  0.    0.  ]
 [ 1.73  6.    1.63  0.  ]
 [ 0.    1.63  1.5   1.44]
 [ 0.    0.    1.44 -1.5 ]]

Verification = A=
[[1. 1. 1. 1.]
 [1. 2. 1. 1.]
 [1. 1. 3. 4.]
 [1. 1. 4. 1.]]
Orthogonal matrix X=
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Tridiagonal matrix J=
[[1. 1. 0. 0.]
 [1. 2. 1. 0.]
 [0. 1. 3. 4.]
 [0. 0. 4. 1.]]

Verification = B=
[[1. 1. 0. 0.]
 [1. 2. 1. 0.]
 [0. 1. 3. 4.]
 [0. 0. 4. 1.]]


In [6]:
import numpy as np
from scipy.linalg import qr

def block_lanczos(A, X1, s):
    n, p = X1.shape
    X = [X1]  # Store block matrices
    H = []  # Store symmetric blocks
    B = []  # Store upper triangular blocks

    H1 = np.dot(np.dot(X1.T, A), X1)
    H.append(H1)

    for i in range(s - 1):
        if i == 0:
            Z = np.dot(A, X[i]) - np.dot(X[i], H[i])
        else:
            Z = np.dot(A, X[i]) - np.dot(X[i], H[i]) - np.dot(X[i - 1], B[i - 1].T)
        Qi, Bi = qr(Z, mode='economic')
        X.append(Qi)
        B.append(Bi)

        
        Hi_plus_1 = np.dot(np.dot(Qi.T, A), Qi)
        H.append(Hi_plus_1)

   
    J = np.zeros((n, n))
    for i in range(s):
        J[i * p:(i + 1) * p, i * p:(i + 1) * p] = H[i]  # Diagonal blocks
        if i < s - 1:
            J[i * p:(i + 1) * p, (i + 1) * p:(i + 2) * p] = B[i]  # Upper blocks
            J[(i + 1) * p:(i + 2) * p, i * p:(i + 1) * p] = B[i].T  # Lower blocks

    X_combined = np.hstack(X)

    return J, X_combined

# Example

n = 6
p = 2
s = 3
A = np.array([[1,1,1,1,1,1],
              [1,1,1,1,1,1],
              [1,1,1,1,1,1],
              [1,1,1,1,1,1],
              [1,1,1,1,1,1],
              [1,1,1,1,1,1],
             ])
X1 = np.random.randn(n, p)
Q, _ = qr(X1, mode='economic')  # Orthonormalize X1

J, X = block_lanczos(A, Q, s)

J, X = block_lanczos(A, Q, s)
np.set_printoptions(precision=2, suppress=True)
print("Block tridiagonal matrix J=")
print(J)

print("Orthogonal matrix X=")
print(X)
# Verify decomposition
print("\nVerification = A=")
print(np.dot(np.dot(X, J), X.T))

Block tridiagonal matrix J=
[[ 0.    0.    0.01  2.66  0.    0.  ]
 [ 0.    1.62  0.    0.    0.    0.  ]
 [ 0.01  0.    4.38  2.66 -2.66 -0.  ]
 [ 2.66  0.    2.66  1.61  0.   -0.03]
 [ 0.    0.   -2.66  0.    1.61 -0.03]
 [ 0.    0.   -0.   -0.03 -0.03  0.  ]]
Orthogonal matrix X=
[[-0.06 -0.4  -0.24 -0.4  -0.4  -0.18]
 [ 0.37 -0.22 -0.35 -0.23 -0.23 -0.69]
 [ 0.32 -0.37 -0.25 -0.37 -0.37  0.01]
 [ 0.41  0.2  -0.6   0.2   0.2  -0.1 ]
 [-0.68  0.26 -0.63  0.27  0.27  0.52]
 [-0.36 -0.74 -0.03 -0.73 -0.73  0.47]]

Verification = A=
[[ 1.14  0.42  0.7  -0.24  0.85  1.96]
 [ 0.42  0.3   0.21  0.64  1.37  0.34]
 [ 0.7   0.21  0.32  0.05  1.14  1.11]
 [-0.24  0.64  0.05  2.23  1.84 -1.65]
 [ 0.85  1.37  1.14  1.84  1.11  0.23]
 [ 1.96  0.34  1.11 -1.65  0.23  4.06]]


In [7]:
# import numpy as np
# # Decompose symmetric matrix A into A = X J X.T
# # A : Symmetric matrix of shape (n, n)
# # x1: Initial normalized vector x1 with x1.T x1 = 1.
# # X : Orthogonal matrix of eigenvectors.
# # J : Tridiagonal matrix

# def lanczos_algorithm(A, x1):
#     n = A.shape[0]
#     X = np.zeros((n, n))
#     J = np.zeros((n, n))
#     X[:, 0] = x1   # Initialize x1 as the first column of X
#     a = np.zeros(n)
#     b = np.zeros(n - 1)
#     a[0] = np.dot(x1.T, np.dot(A, x1))  # Compute a1, first diagonal entry

#     for i in range(1, n):   # Iterative process for i = 1, ..., n-1
#         if i == 1:
#             z_i = np.dot(A, X[:, i - 1]) - a[i - 1] * X[:, i - 1]   # compute zi
#         else:
#             z_i = (np.dot(A, X[:, i - 1]) - a[i - 1] * X[:, i - 1]- b[i - 2] * X[:, i - 2])

       
#         b[i - 1] = np.linalg.norm(z_i)   # Compute b_i as the norm of z_i
#         if b[i - 1] != 0:                    # Normalize z_i to get x_{i+1}
#             X[:, i] = z_i / b[i - 1]

       
#         a[i] = np.dot(X[:, i].T, np.dot(A, X[:, i]))   # Compute a_{i+1}

   
#     for i in range(n):        # Construct J as the tridiagonal matrix
#         J[i, i] = a[i]
#         if i < n - 1:
#             J[i, i + 1] = b[i]
#             J[i + 1, i] = b[i]

#     return X, J




# C = np.array([
#     [1, 1, 1, 1, 1],
#     [1, 2, 1, 1, 0],
#     [1, 1, 3, 4, 1],
#     [1, 1, 4, 1, 1],
#     [1, 0, 1, 1, 4]
# ])

# x1 = np.array([1, 0, 0, 0, 0])

# X, J = lanczos_algorithm(C, x1)

# print("Orthogonal matrix X=")
# print(X)
# print("\nTridiagonal matrix J=")
# print(J)

# # Verify decomposition
# print("\nVerification = C=")
# print(np.dot(np.dot(X, J), X.T))

In [8]:
# import numpy as np
# # Decompose symmetric matrix A into A = X J X.T
# # A : Symmetric matrix of shape (n, n)
# # x1: Initial normalized vector x1 with x1.T x1 = 1.
# # X : Orthogonal matrix of eigenvectors.
# # J : Tridiagonal matrix

# def lanczos_algorithm(A, x1):
#     n = A.shape[0]
#     X = np.zeros((n, n))
#     J = np.zeros((n, n))
#     X[:, 0] = x1   # Initialize x1 as the first column of X
#     a = np.zeros(n)
#     b = np.zeros(n - 1)
#     a[0] = np.dot(x1.T, np.dot(A, x1))  # Compute a1, first diagonal entry

#     for i in range(1, n):   # Iterative process for i = 1, ..., n-1
#         if i == 1:
#             z_i = np.dot(A, x1) - a[0] * x1   # compute zi
#         else:
#             z_i = (np.dot(A, X[:, i]) - a[i] * X[:, i]- b[i - 1] * X[:, i - 1])

       
#         b[i-1] = np.linalg.norm(z_i)   # Compute b_i as the norm of z_i
#         if b[i-1] != 0:                    # Normalize z_i to get x_{i+1}
#             X[:, i+1] = z_i / b[i-1]

       
#         a[i] = np.dot(X[:, i].T, np.dot(A, X[:, i]))   # Compute a_{i+1}

   
#     for i in range(n):        # Construct J as the tridiagonal matrix
#         J[i, i] = a[i]
#         if i < n - 1:
#             J[i, i + 1] = b[i]
#             J[i + 1, i] = b[i]

#     return X, J




# C = np.array([
#     [1, 1, 1, 1, 4],
#     [1, 2, 1, 1, 0],
#     [1, 1, 3, 4, 1],
#     [1, 1, 4, 3, 1],
#     [4, 0, 1, 1, 4]
# ])

# x1 = np.array([1, 0, 0, 0, 0])

# X, J = lanczos_algorithm(C, x1)

# print("Orthogonal matrix X=")
# print(X)
# print("\nTridiagonal matrix J=")
# print(J)

# # Verify decomposition
# print("\nVerification = C=")
# print(np.dot(np.dot(X, J), X.T))

In [9]:
# import numpy as np
# # Decompose symmetric matrix A into A = X J X.T
# # A : Symmetric matrix of shape (n, n)
# # x1: Initial normalized vector x1 with x1.T x1 = 1.
# # X : Orthogonal matrix of eigenvectors.
# # J : Tridiagonal matrix

# def lanczos_algorithm(C, x1):
#     n = C.shape[0]
#     X = np.zeros((n, n))
#     J = np.zeros((n, n))
#     X[:, 0] = x1   # Initialize x1 as the first column of X
#     a = np.zeros(n)
#     b = np.zeros(n - 1)
#     a[0] = np.dot(x1.T, np.dot(C, x1))  # Compute a1, first diagonal entry

#     for i in range(1, n):   # Iterative process for i = 1, ..., n-1
#         if i == 1:
#             z_i = np.dot(C, X[:, i - 1]) - a[i - 1] * X[:, i - 1]   # compute zi
#         else:
#             z_i = (np.dot(C, X[:, i - 1]) - a[i - 1] * X[:, i - 1]- b[i - 2] * X[:, i - 2])

       
#         b[i - 1] = np.linalg.norm(z_i)   # Compute b_i as the norm of z_i
#         if b[i - 1] != 0:                    # Normalize z_i to get x_{i+1}
#             X[:, i] = z_i / b[i - 1]

       
#         a[i] = np.dot(X[:, i].T, np.dot(C, X[:, i]))   # Compute a_{i+1}

   
#     for i in range(n):        # Construct J as the tridiagonal matrix
#         J[i, i] = a[i]
#         if i < n - 1:
#             J[i, i + 1] = b[i]
#             J[i + 1, i] = b[i]

#     return X, J


# #(1) Example symmetric matrix C

# C = np.array([
#     [1, 1, 1, 1, 4],
#     [1, 2, 1, 1, 0],
#     [1, 1, 3, 4, 1],
#     [1, 1, 4, 3, 1],
#     [4, 0, 1, 1, 4]
# ])

# x1 = np.array([1, 0, 0, 0, 0])

# X, J = lanczos_algorithm(C, x1)

# print("Orthogonal matrix X=")
# print(X)
# print("\nTridiagonal matrix J=")
# print(J)

# # Verify decomposition
# print("\nVerification = C=")
# print(np.dot(np.dot(X, J), X.T))


In [10]:
import numpy as np
# Decompose symmetric matrix A into A = X J X.T
# A : Symmetric matrix of shape (n, n)
# x1: Initial normalized vector x1 with x1.T x1 = 1.
# X : Orthogonal matrix of eigenvectors.
# J : Tridiagonal matrix

def lanczos_algorithm(A, x1):
    n = A.shape[0]
    X = np.zeros((n, n))
    J = np.zeros((n, n))
    X[:, 0] = x1   # Initialize x1 as the first column of X
    a = np.zeros(n)
    b = np.zeros(n - 1)
    a[0] = np.dot(x1.T, np.dot(A, x1))  # Compute a1, first diagonal entry

    for i in range(1, n):   # Iterative process for i = 1, ..., n-1
        if i == 1:
            z_i = np.dot(A, X[:, i - 1]) - a[i - 1] * X[:, i - 1]   # compute zi
        else:
            z_i = (np.dot(A, X[:, i - 1]) - a[i - 1] * X[:, i - 1]- b[i - 2] * X[:, i - 2])

       
        b[i - 1] = np.linalg.norm(z_i)   # Compute b_i as the norm of z_i
        if b[i - 1] != 0:                    # Normalize z_i to get x_{i+1}
            X[:, i] = z_i / b[i - 1]

       
        a[i] = np.dot(X[:, i].T, np.dot(A, X[:, i]))   # Compute a_{i+1}

   
    for i in range(n):        # Construct J as the tridiagonal matrix
        J[i, i] = a[i]
        if i < n - 1:
            J[i, i + 1] = b[i]
            J[i + 1, i] = b[i]

    return X, J

A = np.array([
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1]
])

x1 = np.array([1, 0, 0, 0, 0])

X, J = lanczos_algorithm(A, x1)

print("Orthogonal matrix X=")
print(X)
print("\nTridiagonal matrix J=")
print(J)

# Verify decomposition
print("\nVerification = A=")
print(np.dot(np.dot(X, J), X.T))

Orthogonal matrix X=
[[1.  0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]]

Tridiagonal matrix J=
[[1. 2. 0. 0. 0.]
 [2. 4. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Verification = A=
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:

def lanczos_algorithm(A, x1, max_iter=100):
    n = A.shape[0]
    X = np.zeros((n, n))
    J = np.zeros((n, n))
    X[:, 0] = x1   # Initialize x1 as the first column of X
    a = np.zeros(n)
    b = np.zeros(n - 1)
    a[0] = np.dot(x1.T, np.dot(A, x1))  # Compute a1, first diagonal entry

    for i in range(1, n):   # Iterative process for i = 1, ..., n-1
        if i == 1:
            z_i = np.dot(A, X[:, i - 1]) - a[i - 1] * X[:, i - 1]   # compute zi
        else:
            z_i = (np.dot(A, X[:, i - 1]) - a[i - 1] * X[:, i - 1] - b[i - 2] * X[:, i - 2])
        
        b[i - 1] = np.linalg.norm(z_i)   # Compute b_i as the norm of z_i

        # Prevent zero vector issue and restart with a new random orthogonal vector
        if b[i - 1] == 0:
            for _ in range(max_iter):
                z_i = np.random.rand(n)
                # Orthogonalize z_i against all previous X vectors
                for j in range(i):
                    z_i -= np.dot(z_i, X[:, j]) * X[:, j]
                if np.linalg.norm(z_i) > 1e-10:
                    break
            z_i /= np.linalg.norm(z_i)
            b[i - 1] = 0  # Since z_i is orthogonal, set b[i-1] to 0
        
        X[:, i] = z_i / max(b[i - 1], 1e-10)

        a[i] = np.dot(X[:, i].T, np.dot(A, X[:, i]))   # Compute a_{i+1}
   
    for i in range(n):        # Construct J as the tridiagonal matrix
        J[i, i] = a[i]
        if i < n - 1:
            J[i, i + 1] = b[i]
            J[i + 1, i] = b[i]

    return X, J

# Symmetric matrix A
A = np.array([
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1]
])

# Initial vector x1
x1 = np.array([1, 0, 0, 0, 0])

X, J = lanczos_algorithm(A, x1)

print("Orthogonal matrix X=")
print(X)
print("\nTridiagonal matrix J=")
print(J)

# Verify decomposition
print("\nVerification = A=")
print(np.dot(np.dot(X, J), X.T))

Orthogonal matrix X=
[[ 1.00e+00  0.00e+00  0.00e+00  2.62e-05  9.01e-14]
 [ 0.00e+00  5.00e-01 -3.25e+09  3.25e-01  3.25e-01]
 [ 0.00e+00  5.00e-01 -4.06e+09  4.06e-01  4.06e-01]
 [ 0.00e+00  5.00e-01 -1.15e+09  1.15e-01  1.15e-01]
 [ 0.00e+00  5.00e-01  8.46e+09 -8.46e-01 -8.46e-01]]

Tridiagonal matrix J=
[[1.00e+00 2.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [2.00e+00 4.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 1.46e-11 1.46e-01 0.00e+00]
 [0.00e+00 0.00e+00 1.46e-01 1.72e-08 1.46e+09]
 [0.00e+00 0.00e+00 0.00e+00 1.46e+09 2.03e-25]]

Verification = A=
[[ 1.00e+00  1.00e+00  1.00e+00  1.00e+00  1.00e+00]
 [ 1.00e+00  1.54e+08  1.92e+08  5.43e+07 -4.01e+08]
 [ 1.00e+00  1.92e+08  2.40e+08  6.78e+07 -5.00e+08]
 [ 1.00e+00  5.43e+07  6.78e+07  1.92e+07 -1.41e+08]
 [ 1.00e+00 -4.01e+08 -5.00e+08 -1.41e+08  1.04e+09]]


In [12]:
import numpy as np
# Decompose symmetric matrix A into A = X J X.T
# A : Symmetric matrix of shape (n, n)
# x1: Initial normalized vector x1 with x1.T x1 = 1.
# X : Orthogonal matrix of eigenvectors.
# J : Tridiagonal matrix

def lanczos_algorithm(A, x1):
    n = A.shape[0]
    X = np.zeros((n, n))
    J = np.zeros((n, n))
    X[:, 0] = x1   # Initialize x1 as the first column of X
    a = np.zeros(n)
    b = np.zeros(n - 1)
    a[0] = np.dot(x1.T, np.dot(A, x1))  # Compute a1, first diagonal entry

    for i in range(1, n):   # Iterative process for i = 1, ..., n-1
        if i == 1:
            z_i = np.dot(A, X[:, i - 1]) - a[i - 1] * X[:, i - 1]   # compute zi
        else:
            z_i = (np.dot(A, X[:, i - 1]) - a[i - 1] * X[:, i - 1]- b[i - 2] * X[:, i - 2])

       
        b[i - 1] = np.linalg.norm(z_i)   # Compute b_i as the norm of z_i
        if b[i - 1] != 0:                    # Normalize z_i to get x_{i+1}
            X[:, i] = z_i / b[i - 1]

       
        a[i] = np.dot(X[:, i].T, np.dot(A, X[:, i]))   # Compute a_{i+1}

   
    for i in range(n):        # Construct J as the tridiagonal matrix
        J[i, i] = a[i]
        if i < n - 1:
            J[i, i + 1] = b[i]
            J[i + 1, i] = b[i]

    return X, J


np.set_printoptions(precision=2, suppress=True)
A = np.array([
    [1, 1, 1, 1, 1],
    [1, 2, 1, 1, 0],
    [1, 1, 2, 1, 1],
    [1, 1, 1, 2, 1],
    [1, 0, 1, 1, 1]
])

x1 = np.array([1, 0, 0, 0, 0])

X, J = lanczos_algorithm(A, x1)

print("Orthogonal matrix X=")
print(X)
print("\nTridiagonal matrix J=")
print(J)

# Verify decomposition
print("\nVerification = A=")
print(np.dot(np.dot(X, J), X.T))
print(np.dot(X.T, X))

Orthogonal matrix X=
[[ 1.    0.    0.    0.    0.23]
 [ 0.    0.5  -0.15  0.85  0.35]
 [ 0.    0.5   0.45 -0.21  0.61]
 [ 0.    0.5   0.45 -0.21  0.64]
 [ 0.    0.5  -0.75 -0.43  0.18]]

Tridiagonal matrix J=
[[1.   2.   0.   0.   0.  ]
 [2.   4.25 0.83 0.   0.  ]
 [0.   0.83 0.2  0.26 0.  ]
 [0.   0.   0.26 1.55 0.  ]
 [0.   0.   0.   0.   4.87]]

Verification = A=
[[1.26 1.4  1.69 1.72 1.2 ]
 [1.4  2.61 2.06 2.11 0.31]
 [1.69 2.06 3.32 3.42 1.54]
 [1.72 2.11 3.42 3.52 1.57]
 [1.2  0.31 1.54 1.57 1.16]]
[[ 1.    0.    0.    0.    0.23]
 [ 0.    1.    0.    0.    0.9 ]
 [ 0.    0.    1.   -0.    0.38]
 [ 0.    0.   -0.    1.   -0.04]
 [ 0.23  0.9   0.38 -0.04  1.  ]]


In [4]:

import numpy as np

def lanczos_algorithm(A, x1, tol=1e-10):
    n = len(A)
    X = np.zeros((n, n))
    J = np.zeros((n, n))
    
    # Normalize the initial vector x1
    x1 = x1 / np.linalg.norm(x1)
    X[:, 0] = x1
    a1 = np.dot(x1.T, np.dot(A, x1))
    
    a = [a1]
    b = []
    
    for i in range(n - 1):
        if i == 0:
            z_i = np.dot(A, X[:, i]) - X[:, i] * a[i]
        else:
            z_i = np.dot(A, X[:, i]) - X[:, i] * a[i] - X[:, i-1] * b[i-1]
        
        # Check if z_i is close to zero vector
        if np.linalg.norm(z_i) < tol:
            # Choose an arbitrary unit vector orthogonal to all previous X vectors
            z_i = np.random.rand(n)
            for j in range(i + 1):
                z_i -= np.dot(X[:, j], z_i) * X[:, j]
            z_i /= np.linalg.norm(z_i)
            b_i = 0
        else:
            b_i = np.linalg.norm(z_i)
            X[:, i + 1] = z_i / b_i

        a.append(np.dot(X[:, i + 1].T, np.dot(A, X[:, i + 1])))
        b.append(b_i)
    
    # Construct the tridiagonal matrix J
    for i in range(n):
        J[i, i] = a[i]
        if i < n - 1:
            J[i, i + 1] = J[i + 1, i] = b[i]
    
    return J, X

# Example usage: 
# Create a 5x5 symmetric matrix A with all entries as 1
A = np.ones((5, 5))

# Initial vector x1
x1 = np.array([1.0, 0.0, 0.0, 0.0, 0.0])

# Run the algorithm
J, X = lanczos_algorithm(A, x1)

print("Jacobi matrix J:")
print(J)

print("\nOrthogonal matrix X:")
print(X)

Jacobi matrix J:
[[1. 2. 0. 0. 0.]
 [2. 4. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Orthogonal matrix X:
[[1.  0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]]
